STAT_NAME_MAPPING = {
    "MIN": "Minutes",
    "FGM": "Field Goals Made",
    "FGA": "Field Goals Attempted",
    "3PM": "3 Point Field Goals Made",
    "3PA": "3 Point Field Goals Attempted",
    "FTM": "Free Throws Made",
    "FTA": "Free Throws Attempted",
    "ORB": "Offensive Rebounds",
    "DRB": "Deffensive Rebounds",
    "AST": "Assists",
    "STL": "Steals",
    "BLK": "Blocks",
    "TOV": "Turnovers",
    "FLS": "Personal Fouls",
    "NET": "Plus/Minus",
    "PTS": "Points",
}